# ----------------------- #`
#      Main Configs       #
# ----------------------- #

url:
title: michelle tham
email: themichelletham@gmail.com
author: Michelle Tham
description: > # "michelle tham's profile
#copyright: 'Copyright &copy; 2015 Your Name. All Rights Reserved.'
#credits: 'Credits: Landing Page is a free to use, open source Bootstrap theme created by <a href="http://startbootstrap.com/">Start Bootstrap</a>.'

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: email
    url:
  - title: github
    url: https://github.com/yewnikmtham
  - title: linkedin
    url: https://linkedin.com/in/yewnikmtham/

theme: jekyll-theme-minimal
